[project]
name = "continuing-on-langraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.0.1",
    "langchain>=1.0.2",
    "langgraph>=1.0.1",
]
